name: runs python file that greets the user
on: [push]

env: 
  USERNAME: ${{ github.actor }}

jobs:
  hola-mundopy:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.9
      - name: Run py file
        run: python holamundo.py
        
