name: runs python file that greets the user
on: [push]

env: 
  USERNAME: ${{ github.actor }}

jobs:
  holamundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable de entorno
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python Hola-Mundo.py
        
